name: emptyxxl-config
kind: render
files:
  - /opt/emptyxxl/xxl-job-executor.properties.template:/opt/emptyxxl/xxl-job-executor.properties
---
name: emptyxxl-install
kind: once
command:
  - rsync
  - -a
  - /opt/emptyxxl/
  - /target/
