name: release

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker-setup
        uses: docker/setup-buildx-action@v2

      - name: docker-login-ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          architecture: x64

      - name: Run the Maven package phase
        run: mvn --batch-mode --update-snapshots clean package

      - name: docker-login-dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker-meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |-
            ghcr.io/${{ github.repository }}
            ${{ github.repository }}
          tags: |-
            type=raw,value=install,enable={{is_default_branch}}
            type=raw,value=install-pr,enable=${{ github.event_name == 'pull_request' }}
            type=semver,pattern=install-{{version}}
            type=semver,pattern=install-{{major}}.{{minor}}
            type=semver,pattern=install-{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: docker-build-and-push
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
